[package]
name = "mediaproxy-resvg-shim"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
imagesize = "=0.15.0"
resvg = { path = "../resvg", default-features = false, features = ["raster-images", "text"] }
roxmltree = "=0.21.1"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = false
opt-level = 3
panic = "unwind"
strip = "none"

[workspace]
