set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "${MEDIAPROXY_TARGET_PROCESSOR}")

set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    MEDIAPROXY_TARGET_TRIPLE
    MEDIAPROXY_TARGET_PROCESSOR
    MEDIAPROXY_COMPILER_RT_ARCH
    MEDIAPROXY_SYSROOT
    MEDIAPROXY_CLANG
    MEDIAPROXY_CLANGXX
    MEDIAPROXY_LLD
    MEDIAPROXY_AR
    MEDIAPROXY_RANLIB
    MEDIAPROXY_NM
    MEDIAPROXY_STRIP
    MEDIAPROXY_SANITIZER_LOADER
    MEDIAPROXY_ASAN_STATIC_LIBRARY
    MEDIAPROXY_ASAN_LIBRARY
    MEDIAPROXY_ASAN_CXX_LIBRARY)

foreach(required_variable
        MEDIAPROXY_TARGET_TRIPLE
        MEDIAPROXY_TARGET_PROCESSOR
        MEDIAPROXY_COMPILER_RT_ARCH
        MEDIAPROXY_SYSROOT
        MEDIAPROXY_CLANG
        MEDIAPROXY_CLANGXX
        MEDIAPROXY_LLD
        MEDIAPROXY_AR
        MEDIAPROXY_RANLIB
        MEDIAPROXY_NM
        MEDIAPROXY_STRIP
        MEDIAPROXY_SANITIZER_LOADER
        MEDIAPROXY_ASAN_STATIC_LIBRARY
        MEDIAPROXY_ASAN_LIBRARY
        MEDIAPROXY_ASAN_CXX_LIBRARY)
    if(NOT DEFINED ${required_variable})
        message(FATAL_ERROR
            "Sanitizer toolchain variable ${required_variable} is required")
    endif()
endforeach()

set(CMAKE_C_COMPILER "${MEDIAPROXY_CLANG}")
set(CMAKE_CXX_COMPILER "${MEDIAPROXY_CLANGXX}")
set(CMAKE_C_COMPILER_TARGET "${MEDIAPROXY_TARGET_TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${MEDIAPROXY_TARGET_TRIPLE}")
set(CMAKE_LINKER "${MEDIAPROXY_LLD}")
set(CMAKE_AR "${MEDIAPROXY_AR}")
set(CMAKE_RANLIB "${MEDIAPROXY_RANLIB}")
set(CMAKE_NM "${MEDIAPROXY_NM}")
set(CMAKE_STRIP "${MEDIAPROXY_STRIP}")
set(CMAKE_SYSROOT "${MEDIAPROXY_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${MEDIAPROXY_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

get_filename_component(sanitizer_loader_directory
    "${MEDIAPROXY_SANITIZER_LOADER}" DIRECTORY)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_FLAGS_INIT
    "-nostdinc++ -isystem ${MEDIAPROXY_SYSROOT}/usr/include/c++/v1")
set(CMAKE_EXE_LINKER_FLAGS_INIT
    "-fuse-ld=lld -pie -nostdlib -Wl,--dynamic-linker,/lib/ld-musl-${MEDIAPROXY_COMPILER_RT_ARCH}.so.1 ${MEDIAPROXY_SYSROOT}/usr/lib/Scrt1.o ${MEDIAPROXY_SYSROOT}/usr/lib/crti.o ${MEDIAPROXY_SYSROOT}/usr/lib/linux/clang_rt.crtbegin-${MEDIAPROXY_COMPILER_RT_ARCH}.o")
set(sanitizer_runtime_libraries
    "-Wl,--whole-archive ${MEDIAPROXY_ASAN_STATIC_LIBRARY} ${MEDIAPROXY_ASAN_LIBRARY} ${MEDIAPROXY_ASAN_CXX_LIBRARY} -Wl,--no-whole-archive")
set(CMAKE_C_STANDARD_LIBRARIES_INIT
    "${sanitizer_runtime_libraries} -L${sanitizer_loader_directory} -L${MEDIAPROXY_SYSROOT}/usr/lib -Wl,--start-group -lunwind -lc ${MEDIAPROXY_SYSROOT}/usr/lib/linux/libclang_rt.builtins-${MEDIAPROXY_COMPILER_RT_ARCH}.a -Wl,--end-group ${MEDIAPROXY_SYSROOT}/usr/lib/linux/clang_rt.crtend-${MEDIAPROXY_COMPILER_RT_ARCH}.o ${MEDIAPROXY_SYSROOT}/usr/lib/crtn.o")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT
    "${sanitizer_runtime_libraries} -L${sanitizer_loader_directory} -L${MEDIAPROXY_SYSROOT}/usr/lib -Wl,--start-group -lc++ -lc++abi -lunwind -lc ${MEDIAPROXY_SYSROOT}/usr/lib/linux/libclang_rt.builtins-${MEDIAPROXY_COMPILER_RT_ARCH}.a -Wl,--end-group ${MEDIAPROXY_SYSROOT}/usr/lib/linux/clang_rt.crtend-${MEDIAPROXY_COMPILER_RT_ARCH}.o ${MEDIAPROXY_SYSROOT}/usr/lib/crtn.o")
